// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8jtF_bDjOiS7hzimh7OJYDwoMPB4TTg',
    appId: '1:998618441031:web:eeb034717e793961809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    authDomain: 'valorhub-ea8ff.firebaseapp.com',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9gRJuqZl76khXsGGcuvAkoASZ580Zrw',
    appId: '1:998618441031:android:d70a2e4af5168a0a809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tY1NtbNySGAlF9XOu-u8h-Fy2wxUAYU',
    appId: '1:998618441031:ios:4f7bbf7bf255d368809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
    iosBundleId: 'com.example.templateFlutter',
  );
}
