// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8jtF_bDjOiS7hzimh7OJYDwoMPB4TTg',
    appId: '1:998618441031:web:eeb034717e793961809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    authDomain: 'valorhub-ea8ff.firebaseapp.com',
    databaseURL: 'https://valorhub-ea8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9gRJuqZl76khXsGGcuvAkoASZ580Zrw',
    appId: '1:998618441031:android:d70a2e4af5168a0a809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    databaseURL: 'https://valorhub-ea8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tY1NtbNySGAlF9XOu-u8h-Fy2wxUAYU',
    appId: '1:998618441031:ios:4f7bbf7bf255d368809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    databaseURL: 'https://valorhub-ea8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
    androidClientId: '998618441031-20t9egauh25tppobs2l8qj0d05efodo9.apps.googleusercontent.com',
    iosClientId: '998618441031-4hv0h3tr83meoj05mbf44752g59v1nad.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tY1NtbNySGAlF9XOu-u8h-Fy2wxUAYU',
    appId: '1:998618441031:ios:4f7bbf7bf255d368809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    databaseURL: 'https://valorhub-ea8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
    androidClientId: '998618441031-20t9egauh25tppobs2l8qj0d05efodo9.apps.googleusercontent.com',
    iosClientId: '998618441031-4hv0h3tr83meoj05mbf44752g59v1nad.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb8jtF_bDjOiS7hzimh7OJYDwoMPB4TTg',
    appId: '1:998618441031:web:44ad9dc5005cacac809862',
    messagingSenderId: '998618441031',
    projectId: 'valorhub-ea8ff',
    authDomain: 'valorhub-ea8ff.firebaseapp.com',
    databaseURL: 'https://valorhub-ea8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'valorhub-ea8ff.firebasestorage.app',
  );

}